//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Tyler.Odyssey.API.JobTemplate
{
  using System.Xml.Serialization;
  using Shared;

  // 
  // This source code was auto-generated by xsd, Version=4.6.1055.0.
  // 


  /// <remarks/>
  [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
  [System.SerializableAttribute()]
  [System.Diagnostics.DebuggerStepThroughAttribute()]
  [System.ComponentModel.DesignerCategoryAttribute("code")]
  [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
  [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
  public partial class GetDocumentInfoByEntity : BaseGeneratedAPIEntity
  {

    private string entityIDField;

    private DocumentByEntityEntityType entityTypeField;

    private string includeObsoleteField;

    private DocumentByEntityMessageType messageTypeField;

    private BASEREQUIREDZERO nodeIDField;

    private string referenceNumberField;

    private string userIDField;

    private string sourceField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType = "integer")]
    public string EntityID
    {
      get
      {
        return this.entityIDField;
      }
      set
      {
        this.entityIDField = value;
      }
    }

    /// <remarks/>
    public DocumentByEntityEntityType EntityType
    {
      get
      {
        return this.entityTypeField;
      }
      set
      {
        this.entityTypeField = value;
      }
    }

    /// <remarks/>
    public string IncludeObsolete
    {
      get
      {
        return this.includeObsoleteField;
      }
      set
      {
        this.includeObsoleteField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public DocumentByEntityMessageType MessageType
    {
      get
      {
        return this.messageTypeField;
      }
      set
      {
        this.messageTypeField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public BASEREQUIREDZERO NodeID
    {
      get
      {
        return this.nodeIDField;
      }
      set
      {
        this.nodeIDField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string ReferenceNumber
    {
      get
      {
        return this.referenceNumberField;
      }
      set
      {
        this.referenceNumberField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType = "integer")]
    public string UserID
    {
      get
      {
        return this.userIDField;
      }
      set
      {
        this.userIDField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Source
    {
      get
      {
        return this.sourceField;
      }
      set
      {
        this.sourceField = value;
      }
    }
  }

  /// <remarks/>
  [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
  [System.SerializableAttribute()]
  [System.Xml.Serialization.XmlTypeAttribute(TypeName = "DocumentByEntity.EntityType")]
  public enum DocumentByEntityEntityType
  {

    /// <remarks/>
    Case,

    /// <remarks/>
    Event,

    /// <remarks/>
    ServiceEventParty,

    /// <remarks/>
    Bond,

    /// <remarks/>
    Warrant,

    /// <remarks/>
    Exhibit,

    /// <remarks/>
    Party,

    /// <remarks/>
    ProtectionOrder,
  }

  /// <remarks/>
  [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
  [System.SerializableAttribute()]
  [System.Xml.Serialization.XmlTypeAttribute(TypeName = "DocumentByEntity.MessageType")]
  public enum DocumentByEntityMessageType
  {

    /// <remarks/>
    GetDocumentInfoByEntity,
  }

  /// <remarks/>
  [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
  [System.SerializableAttribute()]
  [System.Xml.Serialization.XmlTypeAttribute(TypeName = "BASE.REQUIREDZERO")]
  public enum BASEREQUIREDZERO
  {

    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("0")]
    Item0,
  }
}
