//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Tyler.Odyssey.API.JobTemplate
{
  using System.Xml.Serialization;
  using Shared;

  // 
  // This source code was auto-generated by xsd, Version=4.6.1055.0.
  // 


  /// <remarks/>
  [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
  [System.SerializableAttribute()]
  [System.Diagnostics.DebuggerStepThroughAttribute()]
  [System.ComponentModel.DesignerCategoryAttribute("code")]
  [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
  [System.Xml.Serialization.XmlRootAttribute(Namespace = "", ElementName = "Message", IsNullable = false)]
  public partial class GetDocumentEntity : BaseGeneratedAPIEntity
  {

    private string versionIDField;

    private string itemField;

    private ItemChoiceType itemElementNameField;

    private GetDocumentMessageType messageTypeField;

    private BASEREQUIREDZERO nodeIDField;

    private string referenceNumberField;

    private string userIDField;

    private string sourceField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType = "integer")]
    public string VersionID
    {
      get
      {
        return this.versionIDField;
      }
      set
      {
        this.versionIDField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("FilePath", typeof(string))]
    [System.Xml.Serialization.XmlElementAttribute("IncludeEmbeddedDocument", typeof(string), DataType = "normalizedString")]
    [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemElementName")]
    public string Item
    {
      get
      {
        return this.itemField;
      }
      set
      {
        this.itemField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public ItemChoiceType ItemElementName
    {
      get
      {
        return this.itemElementNameField;
      }
      set
      {
        this.itemElementNameField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public GetDocumentMessageType MessageType
    {
      get
      {
        return this.messageTypeField;
      }
      set
      {
        this.messageTypeField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public BASEREQUIREDZERO NodeID
    {
      get
      {
        return this.nodeIDField;
      }
      set
      {
        this.nodeIDField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string ReferenceNumber
    {
      get
      {
        return this.referenceNumberField;
      }
      set
      {
        this.referenceNumberField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType = "integer")]
    public string UserID
    {
      get
      {
        return this.userIDField;
      }
      set
      {
        this.userIDField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Source
    {
      get
      {
        return this.sourceField;
      }
      set
      {
        this.sourceField = value;
      }
    }
  }

  /// <remarks/>
  [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
  [System.SerializableAttribute()]
  [System.Xml.Serialization.XmlTypeAttribute(IncludeInSchema = false)]
  public enum ItemChoiceType
  {

    /// <remarks/>
    FilePath,

    /// <remarks/>
    IncludeEmbeddedDocument,
  }

  /// <remarks/>
  [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
  [System.SerializableAttribute()]
  [System.Xml.Serialization.XmlTypeAttribute(TypeName = "GetDocument.MessageType")]
  public enum GetDocumentMessageType
  {

    /// <remarks/>
    GetDocument,
  }

  ///// <remarks/>
  //[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
  //[System.SerializableAttribute()]
  //[System.Xml.Serialization.XmlTypeAttribute(TypeName = "BASE.REQUIREDZERO")]
  //public enum BASEREQUIREDZERO
  //{

  //  /// <remarks/>
  //  [System.Xml.Serialization.XmlEnumAttribute("0")]
  //  Item0,
  //}
}