//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tyler.Odyssey.API.JobTemplate
{
  using System.Xml.Serialization;
  using Shared;
  // 
  // This source code was auto-generated by xsd, Version=4.6.1055.0.
  // 


  /// <remarks/>
  [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
  [System.SerializableAttribute()]
  [System.Diagnostics.DebuggerStepThroughAttribute()]
  [System.ComponentModel.DesignerCategoryAttribute("code")]
  [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
  [System.Xml.Serialization.XmlRootAttribute(Namespace = "", ElementName = "Result", IsNullable = false)]
  public partial class GetDocumentResultEntity
  {

    private string[] filePathField;

    private LOCALEMBEDDEDDOCUMENT[] embeddedDocumentField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("FilePath")]
    public string[] FilePath
    {
      get
      {
        return this.filePathField;
      }
      set
      {
        this.filePathField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("EmbeddedDocument")]
    public LOCALEMBEDDEDDOCUMENT[] EmbeddedDocument
    {
      get
      {
        return this.embeddedDocumentField;
      }
      set
      {
        this.embeddedDocumentField = value;
      }
    }
  }

  /// <remarks/>
  [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
  [System.SerializableAttribute()]
  [System.Diagnostics.DebuggerStepThroughAttribute()]
  [System.ComponentModel.DesignerCategoryAttribute("code")]
  [System.Xml.Serialization.XmlTypeAttribute(TypeName = "LOCAL.EMBEDDEDDOCUMENT")]
  public partial class LOCALEMBEDDEDDOCUMENT
  {

    private string documentField;

    private string extensionField;

    /// <remarks/>
    public string Document
    {
      get
      {
        return this.documentField;
      }
      set
      {
        this.documentField = value;
      }
    }

    /// <remarks/>
    public string Extension
    {
      get
      {
        return this.extensionField;
      }
      set
      {
        this.extensionField = value;
      }
    }
  }
}